### ISSUE TITLE
Find an alternative to pytorch's untyped decorators to enable inference mode

### ISSUE THREAD

**Issue by goergen95** [goergen95/seapig#25]
mypy currently throws errors for untyped decorators enabling inference mode re-introduced in 97d7578:

```
Run mypy --install-types --non-interactive .
seapig/scores/base.py:157: error: Untyped decorator makes function "score"
untyped  [untyped-decorator]
        @torch.inference_mode()
         ^~~~~~~~~~~~~~~~~~~~~~
seapig/scores/base.py:181: error: Untyped decorator makes function "select"
untyped  [untyped-decorator]
        @torch.inference_mode()
         ^~~~~~~~~~~~~~~~~~~~~~
seapig/model.py:21: error: Untyped decorator makes function "forward" untyped 
[untyped-decorator]
        @torch.inference_mode()
         ^~~~~~~~~~~~~~~~~~~~~~
seapig/scores/embed.py:93: error: Untyped decorator makes function
"_load_parquet" untyped  [untyped-decorator]
        @torch.inference_mode()
         ^~~~~~~~~~~~~~~~~~~~~~
seapig/scores/embed.py:118: error: Untyped decorator makes function "_embed"
untyped  [untyped-decorator]
        @torch.inference_mode()
         ^~~~~~~~~~~~~~~~~~~~~~
seapig/scores/pyod.py:164: error: Untyped decorator makes function "score"
untyped  [untyped-decorator]
        @torch.inference_mode()
         ^~~~~~~~~~~~~~~~~~~~~~
seapig/scores/knn.py:268: error: Untyped decorator makes function "_distance"
untyped  [untyped-decorator]
        @torch.inference_mode()
         ^~~~~~~~~~~~~~~~~~~~~~
seapig/scores/knn.py:328: error: Untyped decorator makes function "_distance"
untyped  [untyped-decorator]
        @torch.inference_mode()
         ^~~~~~~~~~~~~~~~~~~~~~
seapig/scores/knn.py:394: error: Untyped decorator makes function "_distance"
untyped  [untyped-decorator]
        @torch.inference_mode()
         ^~~~~~~~~~~~~~~~~~~~~~
Found 9 errors in 5 files (checked 9 source files)

```

**Comment by goergen95** [comment]
False positive since the errors are no longer flagged in an environment which was correctly setup.
